import { createHash } from "node:crypto";
import { existsSync, mkdirSync, renameSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { safeError } from "../core/client.js";
import type { ProjectStatus } from "../core/types.js";
import { CapabilityRuntime } from "../research/capabilities.js";

export interface CapabilityCommandHost {
  runtime(ctx: ExtensionContext): Promise<CapabilityRuntime | null>;
  status(ctx: ExtensionContext): Promise<ProjectStatus | null>;
}

export function registerCapabilityFeatures(pi: ExtensionAPI, host: CapabilityCommandHost): void {
  const capabilities = async (_args: string, ctx: ExtensionContext) => { const runtime = await host.runtime(ctx); if (!runtime) return; try { const catalog = await runtime.catalog(); ctx.ui.notify(catalog.map((item) => `${item.id}@${item.version} · ${item.operations.join(", ")} · side effects: ${item.sideEffects.join(", ") || "none"}`).join("\n"), "info"); } catch (error) { fail(ctx, error); } };
  const capability = async (args: string, ctx: ExtensionContext) => { const runtime = await host.runtime(ctx); if (!runtime) return; const separator = args.indexOf(" "), capabilityId = separator < 0 ? args.trim() : args.slice(0, separator).trim(), raw = separator < 0 ? "" : args.slice(separator + 1).trim(); if (!capabilityId || !raw) return ctx.ui.notify("Capability ID and input JSON are required.", "warning"); let input; try { input = JSON.parse(raw); } catch { return ctx.ui.notify("Capability input must be valid JSON.", "error"); } if (!(await ctx.ui.confirm("Invoke scientific capability?", `${capabilityId}\nCore applies capability-specific scientific and human gates.`))) return; try { const data = await runtime.invoke(capabilityId, input, "user"); ctx.ui.notify(JSON.stringify(data, null, 2).slice(0, 8000), "info"); } catch (error) { fail(ctx, error); } };
  const report = async (args: string, ctx: ExtensionContext) => { const runtime = await host.runtime(ctx), status = await host.status(ctx); if (!runtime || !status) return; const path = resolve(ctx.cwd, args.trim() || `${status.project.title.replace(/[^\p{L}\p{N}._-]+/gu, "-")}-report.md`); if (existsSync(path) && !(await ctx.ui.confirm("Overwrite report?", path))) return; const source = { project: status.project, questionCount: status.questions.length, eventCount: status.persistence.eventCount, confirmationObserved: status.confirmationObserved }, sourceHash = createHash("sha256").update(JSON.stringify(source)).digest("hex"), facts = [{ id: "project.status", kind: "scope", value: status.project.status, unit: null, sourceObjectId: status.project.id, sourcePath: "project.status", sourceHash }, { id: "project.question_count", kind: "runtime", value: status.questions.length, unit: "questions", sourceObjectId: status.project.id, sourcePath: "questions.length", sourceHash }, { id: "project.event_count", kind: "runtime", value: status.persistence.eventCount, unit: "events", sourceObjectId: status.project.id, sourcePath: "persistence.eventCount", sourceHash }], assertions = facts.map((fact) => ({ factId: fact.id, assertedValue: fact.value, context: "Project summary report" })); try { const data = await runtime.invoke("scientific-writing", { ledgerId: `cli-report-${Date.now()}`, studyId: null, facts, requiredFactIds: facts.map((item) => item.id), assertions, report: { title: status.project.title, blocks: [{ type: "qualitative", text: "This report contains only facts verified by the active Core Project snapshot." }, { type: "fact_table", title: "Verified Project facts", factIds: facts.map((item) => item.id) }] } }, "user"), rendered = data.result?.rendered; if (typeof rendered !== "string") throw new Error("Core did not return a rendered report"); writeAtomic(path, `${rendered}\n`); ctx.ui.notify(`Fact-bound report written: ${path}`, "info"); } catch (error) { fail(ctx, error); } };
  pi.registerCommand("research-capabilities", { description: "List the seven public scientific capabilities", handler: capabilities });
  pi.registerCommand("capabilities", { description: "列出科研能力", handler: capabilities });
  pi.registerCommand("research-capability", { description: "Invoke a public capability: /research-capability <id> <input-json>", handler: capability });
  pi.registerCommand("capability", { description: "调用科研能力：/capability <id> <input-json>", handler: capability });
  pi.registerCommand("research-report", { description: "Render a fact-bound Project report: /research-report <path>", handler: report });
  pi.registerCommand("report", { description: "生成当前项目报告：/report [path]", handler: report });

  pi.registerTool({ name: "research_capability", label: "Scientific capability", description: "List or invoke versioned public scientific capabilities. Human-only capability operations remain agent-authenticated and Core may reject them.", parameters: Type.Object({ action: Type.Union([Type.Literal("catalog"), Type.Literal("invoke")]), capability: Type.Optional(Type.String({ minLength: 1 })), input: Type.Optional(Type.Unknown()) }, { additionalProperties: false }), async execute(_id, params, _signal, _update, ctx) { const runtime = await host.runtime(ctx); if (!runtime) return toolError("No verified Project is active."); try { if (params.action === "catalog") return toolSuccess({ capabilities: await runtime.catalog() }); if (!params.capability || params.input === undefined) return toolError("capability and input are required."); if (!(await ctx.ui.confirm("Invoke scientific capability?", `${params.capability}\nThe request remains agent-authenticated; Core enforces human-only gates.`))) return toolError("User cancelled capability invocation."); return toolSuccess(await runtime.invoke(params.capability, params.input, "agent")); } catch (error) { return toolError(safeError(error)); } } });
}

function writeAtomic(path: string, value: string) { mkdirSync(dirname(path), { recursive: true }); const temporary = `${path}.${process.pid}.tmp`; writeFileSync(temporary, value, { mode: 0o600 }); renameSync(temporary, path); }
function fail(ctx: ExtensionContext, error: unknown) { ctx.ui.notify(`Scientific capability failed: ${safeError(error)}`, "error"); }
function toolSuccess(value: unknown) { return { content: [{ type: "text" as const, text: JSON.stringify(value, null, 2).slice(0, 16_000) }], details: { publicCapability: true } }; }
function toolError(message: string) { return { content: [{ type: "text" as const, text: message.slice(0, 2000) }], details: { code: "CAPABILITY_FAILED" }, isError: true }; }
