import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { safeError } from "../core/client.js";
import { PluginRuntime, type PluginDescriptor } from "../research/plugins.js";

export interface PluginCommandHost { runtime(ctx: ExtensionContext): Promise<PluginRuntime | null> }

export function registerPluginFeatures(pi: ExtensionAPI, host: PluginCommandHost): void {
  pi.registerCommand("research-plugin-search", { description: "Search Core research plugins without executing code", handler: async (args, ctx) => { const runtime = await host.runtime(ctx); if (!runtime) return; try { const plugins = await runtime.search(args.trim()); ctx.ui.notify(pluginList(plugins), "info"); } catch (error) { fail(ctx, error); } } });
  pi.registerCommand("research-plugin-inspect", { description: "Inspect a Core research plugin descriptor", handler: async (args, ctx) => { const runtime = await host.runtime(ctx); if (!runtime || !args.trim()) return ctx.ui.notify("Descriptor ID is required.", "warning"); try { ctx.ui.notify(pluginDetails(await runtime.inspect(args.trim())), "info"); } catch (error) { fail(ctx, error); } } });
  pi.registerCommand("research-plugin-source-add", { description: "Add and statically refresh a Core plugin source", handler: async (args, ctx) => {
    const runtime = await host.runtime(ctx); if (!runtime) return;
    const [kindRaw, location, ...labelParts] = args.trim().split(/\s+/), kind = kindRaw as "local" | "git" | "npm" | "pi_config";
    if (!(["local", "git", "npm", "pi_config"] as string[]).includes(kind) || !location) return ctx.ui.notify("Usage: /research-plugin-source-add local|git|npm|pi_config <location> [label]", "warning");
    if (!(await ctx.ui.confirm("Add Core plugin source?", `${kind} · ${location}\n\nRefresh performs static inspection and does not execute plugin code.`))) return;
    try { const source = await runtime.addSource(kind, location, labelParts.join(" ") || location); const refreshed = await runtime.refreshSource(source.id); ctx.ui.notify(`Core research plugin source refreshed · ${refreshed.plugins?.length ?? 0} descriptor(s). Pi UI packages remain managed by Pi /packages.`, "info"); } catch (error) { fail(ctx, error); }
  } });
  pi.registerCommand("research-plugin-source-refresh", { description: "Statically refresh a Core plugin source without executing plugin code", handler: async (args, ctx) => { const runtime = await host.runtime(ctx); if (!runtime || !args.trim()) return ctx.ui.notify("Source ID is required.", "warning"); try { const refreshed = await runtime.refreshSource(args.trim()); ctx.ui.notify(`Core plugin source refreshed · ${refreshed.plugins?.length ?? 0} descriptor(s) · static inspection only.`, "info"); } catch (error) { fail(ctx, error); } } });
  pi.registerCommand("research-plugin-install", { description: "Install a Core research plugin after permission approval", handler: async (args, ctx) => {
    const runtime = await host.runtime(ctx); if (!runtime) return; const [descriptorId, scopeRaw] = args.trim().split(/\s+/), scope = scopeRaw === "workspace" ? "workspace" : "project"; if (!descriptorId) return ctx.ui.notify("Usage: /research-plugin-install <descriptor-id> [project|workspace]", "warning");
    try { const descriptor = await runtime.inspect(descriptorId); if (!(await approveDescriptor(ctx, "Install Core research plugin?", descriptor, scope))) return; const installation = await runtime.install(descriptor, scope); ctx.ui.notify(`Installed ${installation.pluginId}@${installation.version} · ${installation.status}. Enable explicitly when ready.`, "info"); } catch (error) { fail(ctx, error); }
  } });
  for (const operation of ["enable", "disable", "remove"] as const) pi.registerCommand(`research-plugin-${operation}`, { description: `${operation} a Core research plugin installation`, handler: async (args, ctx) => {
    const runtime = await host.runtime(ctx); if (!runtime || !args.trim()) return ctx.ui.notify("Installation ID is required.", "warning");
    try { const installation = await runtime.findInstallation(args.trim()); if (!(await ctx.ui.confirm(`${capitalize(operation)} Core research plugin?`, `${installation.pluginId}@${installation.version} · ${installation.scope}\nPi UI package state is unaffected.`))) return; const result = await runtime[operation](installation); ctx.ui.notify(`${capitalize(operation)}d ${result.pluginId} · ${result.status}`, "info"); } catch (error) { fail(ctx, error); }
  } });
  pi.registerCommand("research-plugin-update", { description: "Update a Core plugin with explicit permission-diff approval", handler: async (args, ctx) => {
    const runtime = await host.runtime(ctx); if (!runtime) return; const [installationId, descriptorId] = args.trim().split(/\s+/); if (!installationId || !descriptorId) return ctx.ui.notify("Usage: /research-plugin-update <installation-id> <target-descriptor-id>", "warning");
    try { const current = await runtime.findInstallation(installationId), target = await runtime.inspect(descriptorId), added = target.permissions.filter((item) => !current.approvedPermissions.includes(item)), removed = current.approvedPermissions.filter((item) => !target.permissions.includes(item)); const message = `${current.pluginId}: ${current.version} → ${target.version}\nAdded permissions: ${added.join(", ") || "none"}\nRemoved permissions: ${removed.join(", ") || "none"}\nAll target permissions: ${target.permissions.join(", ") || "none"}`; if (!(await ctx.ui.confirm(added.length ? "Approve expanded plugin permissions?" : "Update Core research plugin?", message))) return; const result = await runtime.update(current, target); ctx.ui.notify(`Updated ${result.installation.pluginId} · added permissions: ${result.permissionDiff.added.join(", ") || "none"}`, "info"); } catch (error) { fail(ctx, error); }
  } });

  pi.registerTool({ name: "research_plugins", label: "Research plugins", description: "Search or inspect the Core research plugin catalog. This read-only tool never installs or executes plugin code.", parameters: Type.Object({ action: Type.Union([Type.Literal("search"), Type.Literal("inspect")]), query: Type.Optional(Type.String({ maxLength: 500 })), descriptorId: Type.Optional(Type.String({ minLength: 1 })) }, { additionalProperties: false }), async execute(_id, params, _signal, _update, ctx) { const runtime = await host.runtime(ctx); if (!runtime) return toolError("No verified Project is active."); try { const value = params.action === "inspect" ? params.descriptorId ? await runtime.inspect(params.descriptorId) : null : await runtime.search(params.query ?? ""); if (value === null) return toolError("descriptorId is required for inspect."); return toolSuccess(value); } catch (error) { return toolError(safeError(error)); } } });
}

function pluginList(plugins: PluginDescriptor[]): string { return `Core research plugins (static catalog; no code executed)\n${plugins.slice(0, 30).map((item) => `${item.descriptorId} · ${item.name}@${item.version} · ${item.compatibilityStatus} · permissions: ${item.permissions.join(", ") || "none"}`).join("\n") || "No matches"}\nPi UI extensions/packages are separate and managed with Pi /packages.`.slice(0, 6000); }
function pluginDetails(item: PluginDescriptor): string { return `Core research plugin\n${item.name}@${item.version} · ${item.pluginId}\n${item.description}\nCompatibility: ${item.compatibilityStatus} ${item.compatibilityIssues.join(", ")}\nPermissions: ${item.permissions.join(", ") || "none"}\nSide effects: ${item.sideEffects.join(", ") || "none"}\nContributions: ${Object.entries(item.contributions).flatMap(([kind, values]) => values.map((value) => `${kind}:${value}`)).join(", ") || "none"}\nPi UI package state is separate.`.slice(0, 6000); }
async function approveDescriptor(ctx: ExtensionContext, title: string, descriptor: PluginDescriptor, scope: string): Promise<boolean> { return ctx.ui.confirm(title, `${descriptor.name}@${descriptor.version} · ${scope}\nPermissions: ${descriptor.permissions.join(", ") || "none"}\nSide effects: ${descriptor.sideEffects.join(", ") || "none"}\nSource: ${descriptor.sourceKind}\nThis approves the exact content hash ${descriptor.contentHash.slice(0, 16)}…`); }
function fail(ctx: ExtensionContext, error: unknown) { ctx.ui.notify(`Core plugin operation failed: ${safeError(error)}`, "error"); }
function capitalize(value: string) { return `${value[0]?.toUpperCase() ?? ""}${value.slice(1)}`; }
function toolSuccess(value: unknown) { return { content: [{ type: "text" as const, text: JSON.stringify(value, null, 2).slice(0, 12_000) }], details: { readOnly: true, catalog: "core-research-plugins" } }; }
function toolError(message: string) { return { content: [{ type: "text" as const, text: message.slice(0, 2000) }], details: { code: "PLUGIN_QUERY_FAILED" }, isError: true }; }
