import assert from "node:assert/strict";
import test from "node:test";
import extension,{RESEARCH_EXPLORER_ENTRY} from "../src/extension/index.js";

function harness(entries:any[]=[]){const commands=new Map<string,any>(),tools=new Map<string,any>(),handlers=new Map<string,any>(),renderers=new Map<string,any>(),appended:any[]=[],uiCalls:any[]=[];const pi={registerCommand:(name:string,value:any)=>commands.set(name,value),registerTool:(value:any)=>tools.set(value.name,value),registerEntryRenderer:(name:string,value:any)=>renderers.set(name,value),on:(name:string,value:any)=>handlers.set(name,value),appendEntry:(type:string,data:any)=>appended.push({type,data})};extension(pi as any);const ctx={sessionManager:{getBranch:()=>entries},ui:{notify:(...args:any[])=>uiCalls.push(["notify",...args]),setTitle:(...args:any[])=>uiCalls.push(["title",...args]),setStatus:(...args:any[])=>uiCalls.push(["status",...args]),setWidget:(...args:any[])=>uiCalls.push(["widget",...args])}};return{commands,tools,handlers,renderers,appended,uiCalls,ctx};}

test("C0 extension registers only the bounded diagnostic surface",()=>{const h=harness();assert.deepEqual([...h.commands.keys()],["research-about"]);assert.deepEqual([...h.tools.keys()],["research_c0_echo"]);assert.ok(h.renderers.has(RESEARCH_EXPLORER_ENTRY));for(const event of ["session_start","input","before_agent_start","turn_start","turn_end","session_shutdown"])assert.ok(h.handlers.has(event),event);});

test("input event preserves Pi chat and prevents extension recursion",async()=>{const h=harness();assert.deepEqual(await h.handlers.get("input")({text:"ordinary question",source:"interactive"},h.ctx),{action:"continue"});assert.deepEqual(await h.handlers.get("input")({text:"?research diagnose",source:"interactive"},h.ctx),{action:"transform",text:"Research Explorer C0 diagnostic request: diagnose"});assert.deepEqual(await h.handlers.get("input")({text:"?research recurse",source:"extension"},h.ctx),{action:"continue"});});

test("C0 context injection is honest and durable state excludes secrets",async()=>{const h=harness([{type:"custom",customType:RESEARCH_EXPLORER_ENTRY,data:{schemaVersion:1,phase:"C0",coreStatus:"not_connected",recordedAt:"now"}}]);await h.handlers.get("session_start")({},h.ctx);assert.ok(h.uiCalls.some(call=>call[0]==="widget"&&JSON.stringify(call).includes("Context entry restored")));const injected=await h.handlers.get("before_agent_start")({systemPrompt:"base"},h.ctx);assert.match(injected.systemPrompt,/Core is not connected/);await h.commands.get("research-about").handler("",h.ctx);assert.equal(h.appended.length,1);const serialized=JSON.stringify(h.appended[0]);assert.doesNotMatch(serialized,/token|secret|password|bearer/i);});

test("diagnostic tool truncates details and performs no external action",async()=>{const h=harness(),tool=h.tools.get("research_c0_echo"),result=await tool.execute("call",{text:"bounded"});assert.equal(result.content[0].text,"bounded");assert.deepEqual(result.details,{phase:"C0",bytes:7});});
